# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

from .types import TableConfigInputSchemaItem, TableDataSchemaItem

__all__ = ["TableConfigInputSchemaItem", "TableDataSchemaItem"]
