# This file was auto-generated by Fern from our API Definition.

import typing

BriefingContentConfigMetricsItem = typing.Union[
    typing.Literal["closed", "target", "gap", "at_risk", "pipeline", "created"], typing.Any
]
