# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.unchecked_base_model import UncheckedBaseModel
from .briefing_output import BriefingOutput
from .briefing_run_status import BriefingRunStatus


class BriefingRun(UncheckedBaseModel):
    """
    A briefing run (execution record).
    """

    id: str
    config_id: str
    organization_id: str
    status: BriefingRunStatus
    started_at: typing.Optional[dt.datetime] = None
    completed_at: typing.Optional[dt.datetime] = None
    agent_session_id: typing.Optional[str] = None
    result: typing.Optional[BriefingOutput] = None
    delivery_status: typing.Optional[typing.Dict[str, str]] = None
    error: typing.Optional[str] = None
    created_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .card_block import CardBlock  # noqa: E402, F401, I001
from .columns_block import ColumnsBlock  # noqa: E402, F401, I001
from .row_block import RowBlock  # noqa: E402, F401, I001
from .section_block import SectionBlock  # noqa: E402, F401, I001

update_forward_refs(BriefingRun)
