# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, update_forward_refs
from ..core.unchecked_base_model import UncheckedBaseModel
from .briefing_output_blocks_item import BriefingOutputBlocksItem


class BriefingOutput(UncheckedBaseModel):
    """
    Complete briefing output from agent.
    """

    schema_version: typing.Optional[int] = None
    blocks: typing.List[BriefingOutputBlocksItem]
    generated_at: str
    data_as_of: str
    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


from .card_block import CardBlock  # noqa: E402, F401, I001
from .columns_block import ColumnsBlock  # noqa: E402, F401, I001
from .row_block import RowBlock  # noqa: E402, F401, I001
from .section_block import SectionBlock  # noqa: E402, F401, I001

update_forward_refs(BriefingOutput)
