# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .block_action import BlockAction
from .callout_block_variant import CalloutBlockVariant


class CalloutBlock(UncheckedBaseModel):
    """
    Highlighted callout/alert.
    """

    type: typing.Literal["callout"] = "callout"
    variant: typing.Optional[CalloutBlockVariant] = None
    title: typing.Optional[str] = None
    content: str
    actions: typing.Optional[typing.List[BlockAction]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
