# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from .bullet_list_block import BulletListBlock
from .callout_block import CalloutBlock
from .change_block import ChangeBlock
from .deal_card_block import DealCardBlock
from .divider_block import DividerBlock
from .header_block import HeaderBlock
from .metric_block import MetricBlock
from .stage_card_block import StageCardBlock
from .table_block import TableBlock
from .text_block import TextBlock
from .update_checklist_block import UpdateChecklistBlock

if typing.TYPE_CHECKING:
    from .card_block import CardBlock
    from .columns_block import ColumnsBlock
    from .row_block import RowBlock
    from .section_block import SectionBlock
SectionBlockBlocksItem = typing.Union[
    BulletListBlock,
    CalloutBlock,
    "CardBlock",
    ChangeBlock,
    "ColumnsBlock",
    DealCardBlock,
    DividerBlock,
    HeaderBlock,
    MetricBlock,
    "RowBlock",
    "SectionBlock",
    StageCardBlock,
    TableBlock,
    TextBlock,
    UpdateChecklistBlock,
]
