# This file was auto-generated by Fern from our API Definition.

from ..core.unchecked_base_model import UncheckedBaseModel
import typing
import pydantic
from .multi_page_crawler_settings_output import MultiPageCrawlerSettingsOutput
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class SourceSyncCrawlSettingsOutput(UncheckedBaseModel):
    source_archetype_id: typing.Literal["com.scoutos.crawl"] = "com.scoutos.crawl"
    start_urls: str = pydantic.Field()
    """
    The starting URL for the crawl process.
    """

    crawler_settings: typing.Optional[MultiPageCrawlerSettingsOutput] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
