# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class ToolTarget(UncheckedBaseModel):
    """
    Tool evaluation target (future).

    Evaluates individual tools/functions in isolation.

    Example:
        target = ToolTarget(
            type="tool",
            tool_id="tool_search_products"
        )
    """

    type: typing.Literal["tool"] = "tool"
    revision_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Specific revision/version to evaluate
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Target-specific metadata
    """

    tool_id: str = pydantic.Field()
    """
    Tool ID to evaluate
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
