# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class TypescriptAutomationConfig(UncheckedBaseModel):
    """
    TypeScript function-based automation
    """

    mode: typing.Literal["typescript"] = "typescript"
    button_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Custom text for the run button
    """

    executing_text: typing.Optional[str] = pydantic.Field(default=None)
    """
    Custom text while executing
    """

    function: str = pydantic.Field()
    """
    TypeScript function code
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
