# This file was auto-generated by Fern from our API Definition.

import typing

UpdateFeedbackRequestStatus = typing.Union[
    typing.Literal["new", "open", "in_progress", "resolved", "closed", "wont_fix"], typing.Any
]
