# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .block_action import BlockAction
from .update_checklist_item import UpdateChecklistItem


class UpdateChecklistBlock(UncheckedBaseModel):
    """
    Checklist of CRM updates with action buttons.
    """

    type: typing.Literal["update_checklist"] = "update_checklist"
    id: typing.Optional[str] = None
    title: typing.Optional[str] = None
    items: typing.List[UpdateChecklistItem]
    apply_all_action: typing.Optional[BlockAction] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
