# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class UpdatePreferencesBody(UncheckedBaseModel):
    enabled: typing.Optional[bool] = None
    delivery_time: typing.Optional[str] = None
    timezone: typing.Optional[str] = None
    delivery_channel: typing.Optional[str] = None
    slack_user_id: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
