# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel
from .update_scorer_request_scorer import UpdateScorerRequestScorer


class UpdateScorerRequest(UncheckedBaseModel):
    """
    Request to update a custom scorer
    """

    scorer: UpdateScorerRequestScorer = pydantic.Field()
    """
    Updated scorer configuration
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
