# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
from ..core.unchecked_base_model import UncheckedBaseModel


class UpsertLimitsPayload(UncheckedBaseModel):
    seats: typing.Optional[int] = None
    agent_interactions: typing.Optional[int] = None
    integrations: typing.Optional[int] = None
    workflow_invocations: typing.Optional[int] = None
    active_workflows: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
