# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .workflow_run_event import WorkflowRunEvent
from .workflow_execute_event_data import WorkflowExecuteEventData
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class WorkflowExecuteEvent(UniversalBaseModel):
    name: WorkflowRunEvent
    data: WorkflowExecuteEventData

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
