# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .documents_create_request_body import DocumentsCreateRequestBody
    from .documents_create_request_body_one_value import DocumentsCreateRequestBodyOneValue
    from .documents_create_request_body_three_item_value import DocumentsCreateRequestBodyThreeItemValue
    from .documents_create_request_body_two_item_value import DocumentsCreateRequestBodyTwoItemValue
    from .documents_create_request_body_zero_value import DocumentsCreateRequestBodyZeroValue
    from .documents_update_batch_request_body import DocumentsUpdateBatchRequestBody
    from .documents_update_batch_request_body_one_value import DocumentsUpdateBatchRequestBodyOneValue
    from .documents_update_batch_request_body_three_item_value import DocumentsUpdateBatchRequestBodyThreeItemValue
    from .documents_update_batch_request_body_two_item_value import DocumentsUpdateBatchRequestBodyTwoItemValue
    from .documents_update_batch_request_body_zero_value import DocumentsUpdateBatchRequestBodyZeroValue
_dynamic_imports: typing.Dict[str, str] = {
    "DocumentsCreateRequestBody": ".documents_create_request_body",
    "DocumentsCreateRequestBodyOneValue": ".documents_create_request_body_one_value",
    "DocumentsCreateRequestBodyThreeItemValue": ".documents_create_request_body_three_item_value",
    "DocumentsCreateRequestBodyTwoItemValue": ".documents_create_request_body_two_item_value",
    "DocumentsCreateRequestBodyZeroValue": ".documents_create_request_body_zero_value",
    "DocumentsUpdateBatchRequestBody": ".documents_update_batch_request_body",
    "DocumentsUpdateBatchRequestBodyOneValue": ".documents_update_batch_request_body_one_value",
    "DocumentsUpdateBatchRequestBodyThreeItemValue": ".documents_update_batch_request_body_three_item_value",
    "DocumentsUpdateBatchRequestBodyTwoItemValue": ".documents_update_batch_request_body_two_item_value",
    "DocumentsUpdateBatchRequestBodyZeroValue": ".documents_update_batch_request_body_zero_value",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "DocumentsCreateRequestBody",
    "DocumentsCreateRequestBodyOneValue",
    "DocumentsCreateRequestBodyThreeItemValue",
    "DocumentsCreateRequestBodyTwoItemValue",
    "DocumentsCreateRequestBodyZeroValue",
    "DocumentsUpdateBatchRequestBody",
    "DocumentsUpdateBatchRequestBodyOneValue",
    "DocumentsUpdateBatchRequestBodyThreeItemValue",
    "DocumentsUpdateBatchRequestBodyTwoItemValue",
    "DocumentsUpdateBatchRequestBodyZeroValue",
]
